database:
  default: mysql
  postgres:
    connection: 'postgres://postgres:abc123_@localhost/uiasdb?sslmode=disable'
  mysql:
    connection: 'root:123456@tcp(127.0.0.1:3306)/spdb_driver?charset=utf8&parseTime=True&loc=Local'

registry:
  enable: false
  default: eureka
  etcd:
    addresses:
      - 127.0.0.1:2379
  eureka:
    addresses:
      - http://127.0.0.1:7001/eureka
    ipaddress: 127.0.0.1:10080

fabric:
  config_file: ./config/sdk_config.yaml
  user_name: Admin
  org_name: tanghu-org
  enable_gm: true
  channels:
    - tanghu-st